### PR TITLE
Latex engrave dont wrap white space

### PR DESCRIPTION
**Pull request by gav451**
I have lots of org-mode files with Python source blocks with documentation strings having horizontal and vertical white-space that disappears from the pdf output resulting from the `engraved` source block back-end during LaTeX export. In case of Elisp documentation strings the issue manifests itself less clearly, but is still there: for instance, empty lines in Elisp documentation strings disappear in the pdf output.

I have solved the issue in my `init.el` by overriding `engrave-faces-latex-face-mapper` which explains the coding in this pull request (one could argue that it should be fixed in a preprocessing step before calling `engrave-faces-latex-face-mapper`).

The idea of the fix is to let the LaTeX face mapper wrap only groups of "words joined by blank characters" in LaTeX commands and pass "newlines and other white-space between those groups" on without wrapping.

### CODE REVIEW

**Comment by tecosaur** [comment]
Ok, this looks reasonable. Should it be applied somewhere within `engrave-faces.el` though, or is it only LaTeX that needs this?

**Comment by gav451** [comment]
The white space in HTML output is OK, but I did never check ASCII output.
The origin of the problem is that the generated LaTeX macros don't handle strings containing white space correctly (compilation makes the white space disappear). 
As far as I understand, the ASCII back-end inserts ANSI escape sequences in the correct positions and I suppose that this has no effect on white space.
In conclusion, applying https://github.com/tecosaur/engrave-faces/pull/12/files#diff-ec56437d2b1581a763884f49840b22d6c82a361a34a8fde8a00425f0feaca7b1 to `engrave-faces-latex.el` will close the issue in my opinion.

**Comment by gav451** [comment]
Sorry, I push the wrong button.

**Comment by tecosaur** [comment]
Ok, I've just given this PR a test with the following python code:

```py
class ColouredPoint(Point):
    """ Class for points which are coloured, based on Point

        vertical
        white
        space

        mmmmm."""

    def __init__(self, initX, initY, initCol):
        Point.__init__(self, initX, initY)
        self.colour = initCol

p = ColouredPoint(3, 3, "green")
q = ColouredPoint(6, 7, "red")
r = Point(8, 4)
```

### Current code

image

### This PR

image

So, this change looks good, I'd like to change how this is implemented though. Do you have FSF assignment? If so I'll just amend your commit, otherwise I'll re-implement it.

**Comment by gav451** [comment]
Hmm, I am a bit surprised by the indentation of the current code result.  Do you use tabs instead of spaces? The NumPyDoc [example.py](http://github.com/numpy/numpydoc/blob/main/doc/example.py) is maybe worthwhile testing for more coverage.

I have an FSF Emacs copyright assignment. I am hesitant to copy it here, but I can sent it privately.

**Comment by tecosaur** [comment]
I tried another few examples, everything is looking fine with the tweaked version of this PR I've just force-pushed.

Let me know if you have any final comments on what I've pushed to your branch, otherwise I'll go ahead and merge it.

**Comment by gav451** [comment]
Nitpicking:  the docstring at line 144 contains "...CONTENT With FACES...". Why does "With" start with an uppercase letter?

I have tested your tweaked version of the PR on my org-mode documents  and I am also happy with the output.

**Comment by tecosaur** [comment]
Oh, "With" isn't correct, it's just unrelated, so I would want it to be in a separate docs commit when I get around to it.

Anyway, thanks for bringing this to my attention and sharing a fix :)

**Pull request merged**
